name: download_proxies

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
    # branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 9,21 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    # - name: cache
      # uses: actions/cache@v3
      # with:
        # path: ~/.cache/pip
        # key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        # restore-keys: |
          # ${{ runner.os }}-pip-

    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: requirements
      run: pip install -r ./proxypool/requirements.txt


    # sign netease
    - name: download_proxies_from_url
      run: python ./proxypool/proxyPool.py --download --file ./proxypool/config.yaml --config ./proxypool/default.config --urlfile ./proxypool/source.url --nopush
    - name: 提交抓取
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add proxypool/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 抓取节点"
    - name: 推送抓取
      uses: ad-m/github-push-action@master
      with:
        branch: main

    - name: download_mihomo
      run: wget https://github.com/MetaCubeX/mihomo/releases/download/v1.19.0/mihomo-linux-amd64-compatible-go120-v1.19.0.gz

    - name: extract_mihomo
      run: gzip -d mihomo-linux-amd64-compatible-go120-v1.19.0.gz

    - name: add_execuable
      run: |
        mv mihomo-linux-amd64-compatible-go120-v1.19.0 mihomo
        chmod +x mihomo

    - name: test_with_lite
      run: |
        chmod +x ./proxypool/lite
        ./proxypool/lite --config ./proxypool/config.json --test ./proxypool/config.yaml
        ./proxypool/lite --config ./proxypool/lite-pingonly.json --test ./output.txt
        ./proxypool/lite --config ./proxypool/lite-speed.json --test ./output.txt
      # - name: retest_with_lite
      #   run: ./proxypool/lite --config ./proxypool/lite-pingonly.json --test ./output.txt && ./proxypool/lite --config ./proxypool/lite-speedonly.json --test ./output.txt

      #   # - name: push_output.txt
      #   #   run: mv output.txt ./proxypool/ && python ./proxypool/autoPush.py
    - name: download_proxies_from_local_url
      run: python ./proxypool/proxyPool.py --download --file ./proxypool/config.yaml --config ./proxypool/default.config --urlfile ./proxypool/source.url.local --nopush
    - name: 提交lite筛选
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        mv output.txt ./proxypool/
        git add proxypool/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 抓取节点"
    - name: 推送lite筛选
      uses: ad-m/github-push-action@master
      with:
        branch: main


    - name: run_mihomo
      run: nohup ./mihomo -f ./proxypool/config.yaml > ./proxypool/mihomo.log 2>&1 &

    - name: test_delay
      run: python ./proxypool/proxyPool.py --delay --file ./proxypool/config.yaml --config ./proxypool/default.config --port 17790 --max 1000 --timeout 1500 --nopush


    - name: 提交测试
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add proxypool/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 测速"
    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main
